services:       

# ██████╗ ██████╗  ██████╗ ██╗    ██╗██╗      █████╗ ██████╗ ██████╗ 
# ██╔══██╗██╔══██╗██╔═══██╗██║    ██║██║     ██╔══██╗██╔══██╗██╔══██╗
# ██████╔╝██████╔╝██║   ██║██║ █╗ ██║██║     ███████║██████╔╝██████╔╝
# ██╔═══╝ ██╔══██╗██║   ██║██║███╗██║██║     ██╔══██║██╔══██╗██╔══██╗
# ██║     ██║  ██║╚██████╔╝╚███╔███╔╝███████╗██║  ██║██║  ██║██║  ██║
# ╚═╝     ╚═╝  ╚═╝ ╚═════╝  ╚══╝╚══╝ ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═
                              
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr
    volumes:
      - ${CONFIGPATH}Prowlarr/config:/config
      - ${DATAPATH}Downloads:/downloads
    ports:
      - 9696:9696
    restart: unless-stopped
    env_file:
      - '.env'
      
# ███████╗ ██████╗ ███╗   ██╗ █████╗ ██████╗ ██████╗ 
# ██╔════╝██╔═══██╗████╗  ██║██╔══██╗██╔══██╗██╔══██╗
# ███████╗██║   ██║██╔██╗ ██║███████║██████╔╝██████╔╝
# ╚════██║██║   ██║██║╚██╗██║██╔══██║██╔══██╗██╔══██╗
# ███████║╚██████╔╝██║ ╚████║██║  ██║██║  ██║██║  ██║
# ╚══════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝                                                 
      
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    volumes:
      - ${CONFIGPATH}Sonarr/config:/config
      - ${DATAPATH}:/data
    ports:
      - 8989:8989
    restart: unless-stopped
    env_file:
      - '.env'
      
# ██████╗  █████╗ ██████╗  █████╗ ██████╗ ██████╗ 
# ██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗
# ██████╔╝███████║██║  ██║███████║██████╔╝██████╔╝
# ██╔══██╗██╔══██║██║  ██║██╔══██║██╔══██╗██╔══██╗
# ██║  ██║██║  ██║██████╔╝██║  ██║██║  ██║██║  ██║
# ╚═╝  ╚═╝╚═╝  ╚═╝╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝                                              

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    volumes:
      - ${CONFIGPATH}Radarr/config:/config
      - ${DATAPATH}:/data
    ports:
      - 7878:7878
    restart: unless-stopped
    env_file:
      - '.env'
      
# ██╗     ██╗██████╗  █████╗ ██████╗ ██████╗ 
# ██║     ██║██╔══██╗██╔══██╗██╔══██╗██╔══██╗
# ██║     ██║██║  ██║███████║██████╔╝██████╔╝
# ██║     ██║██║  ██║██╔══██║██╔══██╗██╔══██╗
# ███████╗██║██████╔╝██║  ██║██║  ██║██║  ██║
# ╚══════╝╚═╝╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝
                                             
  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    hostname: lidarr
    volumes:
      - ${CONFIGPATH}Lidarr/config:/config
      - ${DATAPATH}:/data
    ports:
      - 8686:8686
    restart: unless-stopped
    env_file:
      - '.env'
      
# ██████╗ ███████╗ █████╗ ██████╗  █████╗ ██████╗ ██████╗ 
# ██╔══██╗██╔════╝██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗
# ██████╔╝█████╗  ███████║██║  ██║███████║██████╔╝██████╔╝
# ██╔══██╗██╔══╝  ██╔══██║██║  ██║██╔══██║██╔══██╗██╔══██╗
# ██║  ██║███████╗██║  ██║██████╔╝██║  ██║██║  ██║██║  ██║
# ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝
                                                                                                                   
  readarr:
    image: linuxserver/readarr:develop
    container_name: readarr
    hostname: readarr
    volumes:
      - ${CONFIGPATH}Readarr/config:/config
      - ${DATAPATH}:/data
    ports:
      - 8787:8787
    restart: unless-stopped
    env_file:
      - '.env'

# ██╗  ██╗ ██████╗ ███╗   ███╗ █████╗ ██████╗ ██████╗ 
# ██║  ██║██╔═══██╗████╗ ████║██╔══██╗██╔══██╗██╔══██╗
# ███████║██║   ██║██╔████╔██║███████║██████╔╝██████╔╝
# ██╔══██║██║   ██║██║╚██╔╝██║██╔══██║██╔══██╗██╔══██╗
# ██║  ██║╚██████╔╝██║ ╚═╝ ██║██║  ██║██║  ██║██║  ██║
# ╚═╝  ╚═╝ ╚═════╝ ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝
        
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - ${CONFIGPATH}Homarr/configs:/app/data/configs
      - ${DATAPATH}:/data
    ports:
      - '7575:7575'
    env_file:
      - '.env'

#      ██╗███████╗██╗     ██╗  ██╗   ██╗███████╗██╗███╗   ██╗
#      ██║██╔════╝██║     ██║  ╚██╗ ██╔╝██╔════╝██║████╗  ██║
#      ██║█████╗  ██║     ██║   ╚████╔╝ █████╗  ██║██╔██╗ ██║
# ██   ██║██╔══╝  ██║     ██║    ╚██╔╝  ██╔══╝  ██║██║╚██╗██║
# ╚█████╔╝███████╗███████╗███████╗██║   ██║     ██║██║ ╚████║
#  ╚════╝ ╚══════╝╚══════╝╚══════╝╚═╝   ╚═╝     ╚═╝╚═╝  ╚═══╝
     
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    ports:
      - '8096:8096/tcp'   # Jellyfin web interface
      - '7359:7359/udp'   # Network discovery
      - '1900:1900/udp'   # DLNA port
    volumes:
      - ${CONFIGPATH}Jellyfin/config:/config
      - ${DATAPATH}/media:/data/media
    env_file:
      - '.env'
    restart: unless-stopped
          
#  ██████╗ ██████╗ ██╗████████╗████████╗ ██████╗ ██████╗ ██████╗ ███████╗███╗   ██╗████████╗
# ██╔═══██╗██╔══██╗██║╚══██╔══╝╚══██╔══╝██╔═══██╗██╔══██╗██╔══██╗██╔════╝████╗  ██║╚══██╔══╝
# ██║   ██║██████╔╝██║   ██║      ██║   ██║   ██║██████╔╝██████╔╝█████╗  ██╔██╗ ██║   ██║   
# ██║▄▄ ██║██╔══██╗██║   ██║      ██║   ██║   ██║██╔══██╗██╔══██╗██╔══╝  ██║╚██╗██║   ██║   
# ╚██████╔╝██████╔╝██║   ██║      ██║   ╚██████╔╝██║  ██║██║  ██║███████╗██║ ╚████║   ██║   
#  ╚══▀▀═╝ ╚═════╝ ╚═╝   ╚═╝      ╚═╝    ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝   ╚═╝                                                                                          
                                                                                             
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    hostname: qbittorrent
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    volumes:
      - ${CONFIGPATH}qbittorrent/config:/config
      - ${DATAPATH}/downloads:/data/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    environment:
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    healthcheck:
      start_period: 15s
    env_file:
      - '.env'

